<?php

$countries[] = array('name' => 'Afghanistan', 'code' => 'AF');
$countries[] = array('name' => 'Albania', 'code' => 'AL');
$countries[] = array('name' => 'Algeria', 'code' => 'DZ');
$countries[] = array('name' => 'American Samoa', 'code' => 'AS');
$countries[] = array('name' => 'AndorrA', 'code' => 'AD');
$countries[] = array('name' => 'Angola', 'code' => 'AO');
$countries[] = array('name' => 'Anguilla', 'code' => 'AI');
$countries[] = array('name' => 'Antarctica', 'code' => 'AQ');
$countries[] = array('name' => 'Antigua and Barbuda', 'code' => 'AG');
$countries[] = array('name' => 'Argentina', 'code' => 'AR');
$countries[] = array('name' => 'Armenia', 'code' => 'AM');
$countries[] = array('name' => 'Aruba', 'code' => 'AW');
$countries[] = array('name' => 'Australia', 'code' => 'AU');
$countries[] = array('name' => 'Austria', 'code' => 'AT');
$countries[] = array('name' => 'Azerbaijan', 'code' => 'AZ');
$countries[] = array('name' => 'Bahamas', 'code' => 'BS');
$countries[] = array('name' => 'Bahrain', 'code' => 'BH');
$countries[] = array('name' => 'Bangladesh', 'code' => 'BD');
$countries[] = array('name' => 'Barbados', 'code' => 'BB');
$countries[] = array('name' => 'Belarus', 'code' => 'BY');
$countries[] = array('name' => 'Belgium', 'code' => 'BE');
$countries[] = array('name' => 'Belize', 'code' => 'BZ');
$countries[] = array('name' => 'Benin', 'code' => 'BJ');
$countries[] = array('name' => 'Bermuda', 'code' => 'BM');
$countries[] = array('name' => 'Bhutan', 'code' => 'BT');
$countries[] = array('name' => 'Bolivia', 'code' => 'BO');
$countries[] = array('name' => 'Bosnia and Herzegovina', 'code' => 'BA');
$countries[] = array('name' => 'Botswana', 'code' => 'BW');
$countries[] = array('name' => 'Bouvet Island', 'code' => 'BV');
$countries[] = array('name' => 'Brazil', 'code' => 'BR');
$countries[] = array('name' => 'British Indian Ocean Territory', 'code' => 'IO');
$countries[] = array('name' => 'Brunei Darussalam', 'code' => 'BN');
$countries[] = array('name' => 'Bulgaria', 'code' => 'BG');
$countries[] = array('name' => 'Burkina Faso', 'code' => 'BF');
$countries[] = array('name' => 'Burundi', 'code' => 'BI');
$countries[] = array('name' => 'Cambodia', 'code' => 'KH');
$countries[] = array('name' => 'Cameroon', 'code' => 'CM');
$countries[] = array('name' => 'Canada', 'code' => 'CA');
$countries[] = array('name' => 'Cape Verde', 'code' => 'CV');
$countries[] = array('name' => 'Cayman Islands', 'code' => 'KY');
$countries[] = array('name' => 'Central African Republic', 'code' => 'CF');
$countries[] = array('name' => 'Chad', 'code' => 'TD');
$countries[] = array('name' => 'Chile', 'code' => 'CL');
$countries[] = array('name' => 'China', 'code' => 'CN');
$countries[] = array('name' => 'Christmas Island', 'code' => 'CX');
$countries[] = array('name' => 'Cocos (Keeling) Islands', 'code' => 'CC');
$countries[] = array('name' => 'Colombia', 'code' => 'CO');
$countries[] = array('name' => 'Comoros', 'code' => 'KM');
$countries[] = array('name' => 'Congo', 'code' => 'CG');
$countries[] = array('name' => 'Congo, The Democratic Republic of the', 'code' => 'CD');
$countries[] = array('name' => 'Cook Islands', 'code' => 'CK');
$countries[] = array('name' => 'Costa Rica', 'code' => 'CR');
$countries[] = array('name' => 'Cote D\'Ivoire', 'code' => 'CI');
$countries[] = array('name' => 'Croatia', 'code' => 'HR');
$countries[] = array('name' => 'Cuba', 'code' => 'CU');
$countries[] = array('name' => 'Cyprus', 'code' => 'CY');
$countries[] = array('name' => 'Czech Republic', 'code' => 'CZ');
$countries[] = array('name' => 'Denmark', 'code' => 'DK');
$countries[] = array('name' => 'Djibouti', 'code' => 'DJ');
$countries[] = array('name' => 'Dominica', 'code' => 'DM');
$countries[] = array('name' => 'Dominican Republic', 'code' => 'DO');
$countries[] = array('name' => 'Ecuador', 'code' => 'EC');
$countries[] = array('name' => 'Egypt', 'code' => 'EG');
$countries[] = array('name' => 'El Salvador', 'code' => 'SV');
$countries[] = array('name' => 'Equatorial Guinea', 'code' => 'GQ');
$countries[] = array('name' => 'Eritrea', 'code' => 'ER');
$countries[] = array('name' => 'Estonia', 'code' => 'EE');
$countries[] = array('name' => 'Ethiopia', 'code' => 'ET');
$countries[] = array('name' => 'Falkland Islands (Malvinas)', 'code' => 'FK');
$countries[] = array('name' => 'Faroe Islands', 'code' => 'FO');
$countries[] = array('name' => 'Fiji', 'code' => 'FJ');
$countries[] = array('name' => 'Finland', 'code' => 'FI');
$countries[] = array('name' => 'France', 'code' => 'FR');
$countries[] = array('name' => 'French Guiana', 'code' => 'GF');
$countries[] = array('name' => 'French Polynesia', 'code' => 'PF');
$countries[] = array('name' => 'French Southern Territories', 'code' => 'TF');
$countries[] = array('name' => 'Gabon', 'code' => 'GA');
$countries[] = array('name' => 'Gambia', 'code' => 'GM');
$countries[] = array('name' => 'Georgia', 'code' => 'GE');
$countries[] = array('name' => 'Germany', 'code' => 'DE');
$countries[] = array('name' => 'Ghana', 'code' => 'GH');
$countries[] = array('name' => 'Gibraltar', 'code' => 'GI');
$countries[] = array('name' => 'Greece', 'code' => 'GR');
$countries[] = array('name' => 'Greenland', 'code' => 'GL');
$countries[] = array('name' => 'Grenada', 'code' => 'GD');
$countries[] = array('name' => 'Guadeloupe', 'code' => 'GP');
$countries[] = array('name' => 'Guam', 'code' => 'GU');
$countries[] = array('name' => 'Guatemala', 'code' => 'GT');
$countries[] = array('name' => 'Guernsey', 'code' => 'GG');
$countries[] = array('name' => 'Guinea', 'code' => 'GN');
$countries[] = array('name' => 'Guinea-Bissau', 'code' => 'GW');
$countries[] = array('name' => 'Guyana', 'code' => 'GY');
$countries[] = array('name' => 'Haiti', 'code' => 'HT');
$countries[] = array('name' => 'Heard Island and Mcdonald Islands', 'code' => 'HM');
$countries[] = array('name' => 'Holy See (Vatican City State)', 'code' => 'VA');
$countries[] = array('name' => 'Honduras', 'code' => 'HN');
$countries[] = array('name' => 'Hong Kong', 'code' => 'HK');
$countries[] = array('name' => 'Hungary', 'code' => 'HU');
$countries[] = array('name' => 'Iceland', 'code' => 'IS');
$countries[] = array('name' => 'India', 'code' => 'IN');
$countries[] = array('name' => 'Indonesia', 'code' => 'ID');
$countries[] = array('name' => 'Iran, Islamic Republic Of', 'code' => 'IR');
$countries[] = array('name' => 'Iraq', 'code' => 'IQ');
$countries[] = array('name' => 'Ireland', 'code' => 'IE');
$countries[] = array('name' => 'Isle of Man', 'code' => 'IM');
$countries[] = array('name' => 'Israel', 'code' => 'IL');
$countries[] = array('name' => 'Italy', 'code' => 'IT');
$countries[] = array('name' => 'Jamaica', 'code' => 'JM');
$countries[] = array('name' => 'Japan', 'code' => 'JP');
$countries[] = array('name' => 'Jersey', 'code' => 'JE');
$countries[] = array('name' => 'Jordan', 'code' => 'JO');
$countries[] = array('name' => 'Kazakhstan', 'code' => 'KZ');
$countries[] = array('name' => 'Kenya', 'code' => 'KE');
$countries[] = array('name' => 'Kiribati', 'code' => 'KI');
$countries[] = array('name' => 'Korea, Democratic People\'S Republic of', 'code' => 'KP');
$countries[] = array('name' => 'Korea, Republic of', 'code' => 'KR');
$countries[] = array('name' => 'Kuwait', 'code' => 'KW');
$countries[] = array('name' => 'Kyrgyzstan', 'code' => 'KG');
$countries[] = array('name' => 'Lao People\'S Democratic Republic', 'code' => 'LA');
$countries[] = array('name' => 'Latvia', 'code' => 'LV');
$countries[] = array('name' => 'Lebanon', 'code' => 'LB');
$countries[] = array('name' => 'Lesotho', 'code' => 'LS');
$countries[] = array('name' => 'Liberia', 'code' => 'LR');
$countries[] = array('name' => 'Libyan Arab Jamahiriya', 'code' => 'LY');
$countries[] = array('name' => 'Liechtenstein', 'code' => 'LI');
$countries[] = array('name' => 'Lithuania', 'code' => 'LT');
$countries[] = array('name' => 'Luxembourg', 'code' => 'LU');
$countries[] = array('name' => 'Macao', 'code' => 'MO');
$countries[] = array('name' => 'Macedonia, The Former Yugoslav Republic of', 'code' => 'MK');
$countries[] = array('name' => 'Madagascar', 'code' => 'MG');
$countries[] = array('name' => 'Malawi', 'code' => 'MW');
$countries[] = array('name' => 'Malaysia', 'code' => 'MY');
$countries[] = array('name' => 'Maldives', 'code' => 'MV');
$countries[] = array('name' => 'Mali', 'code' => 'ML');
$countries[] = array('name' => 'Malta', 'code' => 'MT');
$countries[] = array('name' => 'Marshall Islands', 'code' => 'MH');
$countries[] = array('name' => 'Martinique', 'code' => 'MQ');
$countries[] = array('name' => 'Mauritania', 'code' => 'MR');
$countries[] = array('name' => 'Mauritius', 'code' => 'MU');
$countries[] = array('name' => 'Mayotte', 'code' => 'YT');
$countries[] = array('name' => 'Mexico', 'code' => 'MX');
$countries[] = array('name' => 'Micronesia, Federated States of', 'code' => 'FM');
$countries[] = array('name' => 'Moldova, Republic of', 'code' => 'MD');
$countries[] = array('name' => 'Monaco', 'code' => 'MC');
$countries[] = array('name' => 'Mongolia', 'code' => 'MN');
$countries[] = array('name' => 'Montserrat', 'code' => 'MS');
$countries[] = array('name' => 'Morocco', 'code' => 'MA');
$countries[] = array('name' => 'Mozambique', 'code' => 'MZ');
$countries[] = array('name' => 'Myanmar', 'code' => 'MM');
$countries[] = array('name' => 'Namibia', 'code' => 'NA');
$countries[] = array('name' => 'Nauru', 'code' => 'NR');
$countries[] = array('name' => 'Nepal', 'code' => 'NP');
$countries[] = array('name' => 'Netherlands', 'code' => 'NL');
$countries[] = array('name' => 'Netherlands Antilles', 'code' => 'AN');
$countries[] = array('name' => 'New Caledonia', 'code' => 'NC');
$countries[] = array('name' => 'New Zealand', 'code' => 'NZ');
$countries[] = array('name' => 'Nicaragua', 'code' => 'NI');
$countries[] = array('name' => 'Niger', 'code' => 'NE');
$countries[] = array('name' => 'Nigeria', 'code' => 'NG');
$countries[] = array('name' => 'Niue', 'code' => 'NU');
$countries[] = array('name' => 'Norfolk Island', 'code' => 'NF');
$countries[] = array('name' => 'Northern Mariana Islands', 'code' => 'MP');
$countries[] = array('name' => 'Norway', 'code' => 'NO');
$countries[] = array('name' => 'Oman', 'code' => 'OM');
$countries[] = array('name' => 'Pakistan', 'code' => 'PK');
$countries[] = array('name' => 'Palau', 'code' => 'PW');
$countries[] = array('name' => 'Palestinian Territory, Occupied', 'code' => 'PS');
$countries[] = array('name' => 'Panama', 'code' => 'PA');
$countries[] = array('name' => 'Papua New Guinea', 'code' => 'PG');
$countries[] = array('name' => 'Paraguay', 'code' => 'PY');
$countries[] = array('name' => 'Peru', 'code' => 'PE');
$countries[] = array('name' => 'Philippines', 'code' => 'PH');
$countries[] = array('name' => 'Pitcairn', 'code' => 'PN');
$countries[] = array('name' => 'Poland', 'code' => 'PL');
$countries[] = array('name' => 'Portugal', 'code' => 'PT');
$countries[] = array('name' => 'Puerto Rico', 'code' => 'PR');
$countries[] = array('name' => 'Qatar', 'code' => 'QA');
$countries[] = array('name' => 'Reunion', 'code' => 'RE');
$countries[] = array('name' => 'Romania', 'code' => 'RO');
$countries[] = array('name' => 'Russian Federation', 'code' => 'RU');
$countries[] = array('name' => 'RWANDA', 'code' => 'RW');
$countries[] = array('name' => 'Saint Helena', 'code' => 'SH');
$countries[] = array('name' => 'Saint Kitts and Nevis', 'code' => 'KN');
$countries[] = array('name' => 'Saint Lucia', 'code' => 'LC');
$countries[] = array('name' => 'Saint Pierre and Miquelon', 'code' => 'PM');
$countries[] = array('name' => 'Saint Vincent and the Grenadines', 'code' => 'VC');
$countries[] = array('name' => 'Samoa', 'code' => 'WS');
$countries[] = array('name' => 'San Marino', 'code' => 'SM');
$countries[] = array('name' => 'Sao Tome and Principe', 'code' => 'ST');
$countries[] = array('name' => 'Saudi Arabia', 'code' => 'SA');
$countries[] = array('name' => 'Senegal', 'code' => 'SN');
$countries[] = array('name' => 'Serbia and Montenegro', 'code' => 'CS');
$countries[] = array('name' => 'Seychelles', 'code' => 'SC');
$countries[] = array('name' => 'Sierra Leone', 'code' => 'SL');
$countries[] = array('name' => 'Singapore', 'code' => 'SG');
$countries[] = array('name' => 'Slovakia', 'code' => 'SK');
$countries[] = array('name' => 'Slovenia', 'code' => 'SI');
$countries[] = array('name' => 'Solomon Islands', 'code' => 'SB');
$countries[] = array('name' => 'Somalia', 'code' => 'SO');
$countries[] = array('name' => 'South Africa', 'code' => 'ZA');
$countries[] = array('name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS');
$countries[] = array('name' => 'Spain', 'code' => 'ES');
$countries[] = array('name' => 'Sri Lanka', 'code' => 'LK');
$countries[] = array('name' => 'Sudan', 'code' => 'SD');
$countries[] = array('name' => 'Suri\'name', 'code' => 'SR');
$countries[] = array('name' => 'Svalbard and Jan Mayen', 'code' => 'SJ');
$countries[] = array('name' => 'Swaziland', 'code' => 'SZ');
$countries[] = array('name' => 'Sweden', 'code' => 'SE');
$countries[] = array('name' => 'Switzerland', 'code' => 'CH');
$countries[] = array('name' => 'Syrian Arab Republic', 'code' => 'SY');
$countries[] = array('name' => 'Taiwan, Province of China', 'code' => 'TW');
$countries[] = array('name' => 'Tajikistan', 'code' => 'TJ');
$countries[] = array('name' => 'Tanzania, United Republic of', 'code' => 'TZ');
$countries[] = array('name' => 'Thailand', 'code' => 'TH');
$countries[] = array('name' => 'Timor-Leste', 'code' => 'TL');
$countries[] = array('name' => 'Togo', 'code' => 'TG');
$countries[] = array('name' => 'Tokelau', 'code' => 'TK');
$countries[] = array('name' => 'Tonga', 'code' => 'TO');
$countries[] = array('name' => 'Trinidad and Tobago', 'code' => 'TT');
$countries[] = array('name' => 'Tunisia', 'code' => 'TN');
$countries[] = array('name' => 'Turkey', 'code' => 'TR');
$countries[] = array('name' => 'Turkmenistan', 'code' => 'TM');
$countries[] = array('name' => 'Turks and Caicos Islands', 'code' => 'TC');
$countries[] = array('name' => 'Tuvalu', 'code' => 'TV');
$countries[] = array('name' => 'Uganda', 'code' => 'UG');
$countries[] = array('name' => 'Ukraine', 'code' => 'UA');
$countries[] = array('name' => 'United Arab Emirates', 'code' => 'AE');
$countries[] = array('name' => 'United Kingdom', 'code' => 'GB');
$countries[] = array('name' => 'United States', 'code' => 'US');
$countries[] = array('name' => 'United States Minor Outlying Islands', 'code' => 'UM');
$countries[] = array('name' => 'Uruguay', 'code' => 'UY');
$countries[] = array('name' => 'Uzbekistan', 'code' => 'UZ');
$countries[] = array('name' => 'Vanuatu', 'code' => 'VU');
$countries[] = array('name' => 'Venezuela', 'code' => 'VE');
$countries[] = array('name' => 'Viet Nam', 'code' => 'VN');
$countries[] = array('name' => 'Virgin Islands, British', 'code' => 'VG');
$countries[] = array('name' => 'Virgin Islands, U.S.', 'code' => 'VI');
$countries[] = array('name' => 'Wallis and Futuna', 'code' => 'WF');
$countries[] = array('name' => 'Western Sahara', 'code' => 'EH');
$countries[] = array('name' => 'Yemen', 'code' => 'YE');
$countries[] = array('name' => 'Zambia', 'code' => 'ZM');
$countries[] = array('name' => 'Zimbabwe', 'code' => 'ZW');

 
